### ISSUE TITLE
Leaking memory

### ISSUE THREAD

**Issue by sbOogway** [gosom/google-maps-scraper#82]
Hi,
Great project bro very well done but in my setup it leaks memory. each time i run it creates a new chrome process .  a simple ```sudo pkill chrome``` gave some memory back.

![chrome_ps](https://github.com/user-attachments/assets/e39b7fc2-ab2c-4648-973d-a56d27a8a6bc)

**Comment by gosom** [comment]
@sbOogway can you please give me some more information?

- OS
- how you start the program ?

**Comment by sbOogway** [comment]
i am in debian and running it through docker. every time i run it, it spawns some (from 6 to 18) threads of chrome in the root directory. should nt be they closed when the scraping job is finished?
![chrome-ps2](https://github.com/user-attachments/assets/699a34d3-2456-4b80-9722-f688c41564ce)

now they re more

**Comment by gosom** [comment]
how often you call it? it requires around 3m to cleanup. 

I assume that you have a web server or similar and you make a request. Do you wait for the program to exist or you sent multiple requests?


when you start the program as it is intended to get started is the behavior the same?

**Comment by sbOogway** [comment]
@gosom 

i restarted the docker container and i run it through the web interface and i get the same problem. i have waited for each job to finish.

**Comment by gosom** [comment]
can you confirm the following:

(1) start the app using the provided docker container in the latest version
(2) the web interface is accessible at localhost:8080
(3) you add a keyword in the form and click the start button
(4) you wait until the job finishes
(5) you click download CSV and it's not empty
(6) after these you can still see open chromium browsers?

**Comment by sbOogway** [comment]
yes. i dont click the download button. i only start the job. why the chromium browsers run in root directory?

**Comment by gosom** [comment]
this is in the docker container not in your host. docker run as root. 

let me check if the same happens to me (Fedora) and let you know

**Comment by sbOogway** [comment]
ok thanks bro, appreciate it.

**Comment by gosom** [comment]
```
docker pull gosom/google-maps-scraper
mkdir -p gmapsdata && docker run -v $PWD/gmapsdata:/gmapsdata -p 8080:8080 gosom/google-maps-scraper -web -data-folder /gmapsdata
```

![image](https://github.com/user-attachments/assets/a646e8e5-9eb1-49f1-9efc-3f6b36317326)

![image](https://github.com/user-attachments/assets/ebd372b6-e48b-4b2e-807e-b879efd8a6b5)


I run the above.

the browsers cleanup up

**Comment by sbOogway** [comment]
ok thanks for the time. i still get the problem but i can work it around with pkill. thanks a lot

**Comment by gosom** [comment]
@sbOogway you are right regarding the above. It is reproduced. 

It has something to do with the way the browser are cleaned up.

**Comment by sbOogway** [comment]
@gosom if u want i can try to fix it. In which files do i have to look roughly?

**Comment by gosom** [comment]
@sbOogway can you try the latest release (v1.5.1). I believe that this is fixed but I was not in the first place able to reproduce consistently. 

FYI: the issue most likely was that in the scrapemate repo the playwright browsers and playwright instance were not closed properly. here is the commit with the fix:

https://github.com/gosom/scrapemate/commit/153bd5a946e1e24ae0e15f2123617f64b8856600

**Comment by sbOogway** [comment]
@gosom i still get it bro

![chrome-ps3](https://github.com/user-attachments/assets/8073a0a0-5a5d-4cfd-86ab-73d901352bbe)

**Comment by gosom** [comment]
have you tried to compile and run from your machine? 
also please double check that you pulled the latest image just in case. 

This is weird, trying to reproduce again

**Comment by gosom** [comment]
![image](https://github.com/user-attachments/assets/ce618d20-9f48-4621-b370-44eb72a814f7)

**Comment by sbOogway** [comment]
yeah bro 

![chrome-ps4](https://github.com/user-attachments/assets/48531200-dd22-47c6-b57f-aa75f8ad5b12)

**Comment by sbOogway** [comment]
i have to go for the day. replying to you tomorrow. have a nice one

**Comment by yeahoffline** [comment]
this is still a issue it seems? large datasets create endless memory until the server dies
